# Cadvisor Docker Compose
# Container metrics

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.51.0
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - TZ=America/Chicago
    volumes:
      - cadvisor-data:/var/lib/cadvisor
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - proxy

volumes:
  cadvisor-data:

networks:
  proxy:
    external: true
