# Calibre Docker Compose
# Ebook management

services:
  calibre:
    image: linuxserver/calibre-web:latest
    container_name: calibre
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      - TZ=America/Chicago
    volumes:
      - calibre-data:/config
    networks:
      - proxy

volumes:
  calibre-data:

networks:
  proxy:
    external: true
