# Jellyfin Docker Compose
# Media server

services:
  jellyfin:
    image: jellyfin/jellyfin:10.10.6
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    environment:
      - TZ=America/Chicago
    volumes:
      - jellyfin-data:/config
      - /mnt/media:/mnt/media:ro
    networks:
      - proxy

volumes:
  jellyfin-data:

networks:
  proxy:
    external: true
