# Keycloak Docker Compose
# Identity provider

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9000:9000"
    environment:
      - TZ=America/Chicago
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - proxy

volumes:
  keycloak-data:

networks:
  proxy:
    external: true
