# Ntfy Docker Compose
# Push notifications

services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    restart: unless-stopped
    ports:
      - "80:80"
      - "9090:8080"
    environment:
      - TZ=America/Chicago
    volumes:
      - ntfy-data:/var/lib/ntfy
    networks:
      - proxy

volumes:
  ntfy-data:

networks:
  proxy:
    external: true
