# Paperless Docker Compose
# Document management

services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - TZ=America/Chicago
    volumes:
      - paperless-data:/usr/src/paperless/data
    networks:
      - proxy

volumes:
  paperless-data:

networks:
  proxy:
    external: true
