# Uptime Kuma Docker Compose
# Uptime monitoring

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - TZ=America/Chicago
    volumes:
      - uptime-kuma-data:/app/data
    networks:
      - proxy

volumes:
  uptime-kuma-data:

networks:
  proxy:
    external: true
